### PR TITLE
Lower api to 9

### PR DESCRIPTION
**Pull request by BLeQuerrec**
It doesn't actually use any APIs that don't exist in 9.

### CODE REVIEW

**Comment by juliocotta** [comment]
+1

**Comment by daniele-athome** [comment]
It can even be lowered to 8 as showed here https://github.com/amulyakhare/TextDrawable/pull/2

**Comment by acrespofn** [comment]
+1!

**Comment by daniele-athome** [comment]
Guys this repo hasn't been touched in months. I don't think the developer is still maintaining it :-(

**Comment by acrespofn** [comment]
Isn't there a working/mainting fork that can be recommended? I noticed https://github.com/acappelli/TextDrawable but its has fallen behind a little bit and doesn't seem to show any activity either

**Comment by daniele-athome** [comment]
No, that fork is also dead, I know for sure. I've copied the source files into my project anyway.

**Pull request closed without merging**
